<?php

use Illuminate\Database\Seeder;

class NavigationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('navigations')->delete();
        
        \DB::table('navigations')->insert(array (
            0 => 
            array (
                'id' => 3,
                'title' => '爱淘宝',
                'navigation_category_id' => 2,
                'url' => 'https://ai.taobao.com/?pid=mm_26820200_7656770_55752061',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 17:20:50',
                'updated_at' => '2019-12-13 17:20:50',
            ),
            1 => 
            array (
                'id' => 4,
                'title' => '京东',
                'navigation_category_id' => 2,
                'url' => 'https://union-click.jd.com/jdc?e=&p=AyIGZRprFDJWWA1FBCVbV0IUWVALHFRBEwQAQB1AWQkrL0llF3sIYyJ3VWR9AmUpXkR3TFVpHRkOIgdTE1IQAxMPXRtrFgsWBFISWx0CIjdVGmtebBM3VR1THQMUA1IdXCUCFgNSGFwRABMEVB1bJQUSDmUSWhwHEgdJGF4UAhsBURNrJTIRN2UrWxUyEjcKXwZIMhAGVB9S&t=W1dCFFlQCxxUQRMEAEAdQFkJ',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 17:22:03',
                'updated_at' => '2019-12-13 17:22:03',
            ),
            2 => 
            array (
                'id' => 5,
                'title' => '优酷网',
                'navigation_category_id' => 3,
                'url' => 'https://www.youku.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 17:24:08',
                'updated_at' => '2019-12-13 17:24:08',
            ),
            3 => 
            array (
                'id' => 6,
                'title' => '知乎',
                'navigation_category_id' => 9,
                'url' => 'https://www.zhihu.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 17:24:34',
                'updated_at' => '2019-12-13 17:24:34',
            ),
            4 => 
            array (
                'id' => 7,
                'title' => '苏宁易购',
                'navigation_category_id' => 2,
                'url' => 'https://www.suning.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:01:50',
                'updated_at' => '2019-12-13 18:01:50',
            ),
            5 => 
            array (
                'id' => 8,
                'title' => '唯品会',
                'navigation_category_id' => 2,
                'url' => 'https://t.vip.com/585OMys',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:02:00',
                'updated_at' => '2019-12-13 18:02:00',
            ),
            6 => 
            array (
                'id' => 9,
                'title' => '聚划算',
                'navigation_category_id' => 2,
                'url' => 'https://s.click.taobao.com/t?e=m%3D2%26s%3D1t1U6XTdQF0cQipKwQzePCperVdZeJviEViQ0P1Vf2kguMN8XjClAh6Ifwu4OR3Xzz6zgI1fZL0vuTCexJ5uFBzJRjY8Yc4N4zPKIuwZymiSm5usamS30eo0BcZWWIRYYA%2FDpPH01wJAFEHVckI7b7Sgd9R%2Fv5WktY4Qt2cZ1lVeY%2By0blbhscYl7w3%2FA2kb',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:02:08',
                'updated_at' => '2019-12-13 18:02:08',
            ),
            7 => 
            array (
                'id' => 10,
                'title' => '当当网',
                'navigation_category_id' => 2,
                'url' => 'http://www.dangdang.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:02:15',
                'updated_at' => '2019-12-13 18:02:15',
            ),
            8 => 
            array (
                'id' => 11,
                'title' => '爱奇艺',
                'navigation_category_id' => 3,
                'url' => 'http://www.iqiyi.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:02:40',
                'updated_at' => '2019-12-13 18:02:40',
            ),
            9 => 
            array (
                'id' => 12,
                'title' => '腾讯视频',
                'navigation_category_id' => 3,
                'url' => 'https://v.qq.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:02:49',
                'updated_at' => '2019-12-13 18:02:49',
            ),
            10 => 
            array (
                'id' => 13,
                'title' => '百度视频',
                'navigation_category_id' => 3,
                'url' => 'http://v.baidu.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:02:58',
                'updated_at' => '2019-12-13 18:02:58',
            ),
            11 => 
            array (
                'id' => 14,
                'title' => '芒果TV',
                'navigation_category_id' => 3,
                'url' => 'https://www.mgtv.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:03:07',
                'updated_at' => '2019-12-13 18:03:07',
            ),
            12 => 
            array (
                'id' => 15,
                'title' => 'Acfun弹幕',
                'navigation_category_id' => 3,
                'url' => 'http://www.acfun.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:03:23',
                'updated_at' => '2019-12-13 18:03:23',
            ),
            13 => 
            array (
                'id' => 16,
                'title' => 'CCTV体育',
                'navigation_category_id' => 5,
                'url' => 'http://sports.cctv.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:03:52',
                'updated_at' => '2019-12-13 18:03:52',
            ),
            14 => 
            array (
                'id' => 17,
                'title' => '虎扑体育',
                'navigation_category_id' => 5,
                'url' => 'https://www.hupu.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:04:04',
                'updated_at' => '2019-12-13 18:04:04',
            ),
            15 => 
            array (
                'id' => 18,
                'title' => '凤凰体育',
                'navigation_category_id' => 5,
                'url' => 'http://sports.ifeng.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:04:17',
                'updated_at' => '2019-12-13 18:04:17',
            ),
            16 => 
            array (
                'id' => 19,
                'title' => '网易体育',
                'navigation_category_id' => 5,
                'url' => 'http://sports.163.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:04:28',
                'updated_at' => '2019-12-13 18:04:28',
            ),
            17 => 
            array (
                'id' => 20,
                'title' => 'NBA中文网',
                'navigation_category_id' => 5,
                'url' => 'https://china.nba.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:04:41',
                'updated_at' => '2019-12-13 18:04:41',
            ),
            18 => 
            array (
                'id' => 21,
                'title' => '直播吧',
                'navigation_category_id' => 5,
                'url' => 'https://www.zhibo8.cc/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:04:52',
                'updated_at' => '2019-12-13 18:04:52',
            ),
            19 => 
            array (
                'id' => 22,
                'title' => '起点中文网',
                'navigation_category_id' => 15,
                'url' => 'https://www.qidian.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:05:03',
                'updated_at' => '2019-12-13 18:05:03',
            ),
            20 => 
            array (
                'id' => 23,
                'title' => '懒人听书',
                'navigation_category_id' => 15,
                'url' => 'http://www.lrts.me/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:05:16',
                'updated_at' => '2019-12-13 18:05:16',
            ),
            21 => 
            array (
                'id' => 24,
                'title' => '喜马拉雅',
                'navigation_category_id' => 15,
                'url' => 'https://www.ximalaya.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:05:32',
                'updated_at' => '2019-12-13 18:05:32',
            ),
            22 => 
            array (
                'id' => 25,
                'title' => '纵横中文网',
                'navigation_category_id' => 15,
                'url' => 'http://www.zongheng.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:05:43',
                'updated_at' => '2019-12-13 18:05:43',
            ),
            23 => 
            array (
                'id' => 26,
                'title' => '红袖添香',
                'navigation_category_id' => 15,
                'url' => 'https://www.hongxiu.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:05:53',
                'updated_at' => '2019-12-13 18:05:53',
            ),
            24 => 
            array (
                'id' => 27,
                'title' => 'QQ阅读',
                'navigation_category_id' => 15,
                'url' => 'http://book.qq.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:06:01',
                'updated_at' => '2019-12-13 18:06:01',
            ),
            25 => 
            array (
                'id' => 28,
                'title' => '东方财富',
                'navigation_category_id' => 14,
                'url' => 'http://www.eastmoney.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:06:16',
                'updated_at' => '2019-12-13 18:06:16',
            ),
            26 => 
            array (
                'id' => 29,
                'title' => '新浪财经',
                'navigation_category_id' => 14,
                'url' => 'https://finance.sina.com.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:06:26',
                'updated_at' => '2019-12-13 18:06:26',
            ),
            27 => 
            array (
                'id' => 30,
                'title' => '雪球',
                'navigation_category_id' => 14,
                'url' => 'https://xueqiu.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:06:37',
                'updated_at' => '2019-12-13 18:06:37',
            ),
            28 => 
            array (
                'id' => 31,
                'title' => '金融界',
                'navigation_category_id' => 14,
                'url' => 'http://www.jrj.com.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:06:49',
                'updated_at' => '2019-12-13 18:06:49',
            ),
            29 => 
            array (
                'id' => 32,
                'title' => '和讯网',
                'navigation_category_id' => 14,
                'url' => 'http://www.hexun.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:07:00',
                'updated_at' => '2019-12-13 18:07:00',
            ),
            30 => 
            array (
                'id' => 33,
                'title' => '凤凰财经',
                'navigation_category_id' => 14,
                'url' => 'http://finance.ifeng.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:07:10',
                'updated_at' => '2019-12-13 18:07:10',
            ),
            31 => 
            array (
                'id' => 34,
                'title' => '携程旅游',
                'navigation_category_id' => 13,
                'url' => 'http://hotels.ctrip.com?AllianceID=11175&sid=555450&ouid=&app=0301C00',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:07:21',
                'updated_at' => '2019-12-13 18:07:21',
            ),
            32 => 
            array (
                'id' => 35,
                'title' => '同程旅游',
                'navigation_category_id' => 13,
                'url' => 'http://www.ly.com?refid=48050718',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:07:30',
                'updated_at' => '2019-12-13 18:07:30',
            ),
            33 => 
            array (
                'id' => 36,
                'title' => '途牛网',
                'navigation_category_id' => 13,
                'url' => 'http://www.tuniu.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:07:40',
                'updated_at' => '2019-12-13 18:07:40',
            ),
            34 => 
            array (
                'id' => 37,
                'title' => '去哪儿',
                'navigation_category_id' => 13,
                'url' => 'https://www.qunar.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:07:50',
                'updated_at' => '2019-12-13 18:07:50',
            ),
            35 => 
            array (
                'id' => 38,
                'title' => '穷游网',
                'navigation_category_id' => 13,
                'url' => 'https://www.qyer.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:08:01',
                'updated_at' => '2019-12-13 18:08:01',
            ),
            36 => 
            array (
                'id' => 39,
                'title' => '驴妈妈',
                'navigation_category_id' => 13,
                'url' => 'https://union.lvmama.com/tnt_cps/cps/newRedirect2.do?source=75484&lvmamakey=4dMp&isNew=new',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:08:17',
                'updated_at' => '2019-12-13 18:08:17',
            ),
            37 => 
            array (
                'id' => 40,
                'title' => '新浪新闻',
                'navigation_category_id' => 4,
                'url' => 'https://news.sina.com.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:08:26',
                'updated_at' => '2019-12-13 18:08:26',
            ),
            38 => 
            array (
                'id' => 41,
                'title' => '环球网',
                'navigation_category_id' => 4,
                'url' => 'http://www.huanqiu.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:08:38',
                'updated_at' => '2019-12-13 18:08:38',
            ),
            39 => 
            array (
                'id' => 42,
                'title' => '搜狐新闻',
                'navigation_category_id' => 4,
                'url' => 'http://news.sohu.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:08:49',
                'updated_at' => '2019-12-13 18:08:49',
            ),
            40 => 
            array (
                'id' => 43,
                'title' => '腾讯门户',
                'navigation_category_id' => 4,
                'url' => 'https://www.qq.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:08:58',
                'updated_at' => '2019-12-13 18:08:58',
            ),
            41 => 
            array (
                'id' => 44,
                'title' => '凤凰资讯',
                'navigation_category_id' => 4,
                'url' => 'http://news.ifeng.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:09:07',
                'updated_at' => '2019-12-13 18:09:16',
            ),
            42 => 
            array (
                'id' => 45,
                'title' => '人民网',
                'navigation_category_id' => 4,
                'url' => 'http://www.people.com.cn',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:09:33',
                'updated_at' => '2019-12-13 18:09:33',
            ),
            43 => 
            array (
                'id' => 46,
                'title' => '汽车之家',
                'navigation_category_id' => 12,
                'url' => 'https://www.autohome.com.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:09:42',
                'updated_at' => '2019-12-13 18:09:42',
            ),
            44 => 
            array (
                'id' => 47,
                'title' => '易车网',
                'navigation_category_id' => 12,
                'url' => 'http://www.bitauto.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:09:51',
                'updated_at' => '2019-12-13 18:09:51',
            ),
            45 => 
            array (
                'id' => 48,
                'title' => '新浪汽车',
                'navigation_category_id' => 12,
                'url' => 'http://auto.sina.com.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:09:59',
                'updated_at' => '2019-12-13 18:09:59',
            ),
            46 => 
            array (
                'id' => 49,
                'title' => '爱卡汽车',
                'navigation_category_id' => 12,
                'url' => 'http://www.xcar.com.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:10:07',
                'updated_at' => '2019-12-13 18:10:07',
            ),
            47 => 
            array (
                'id' => 50,
                'title' => '太平洋汽车',
                'navigation_category_id' => 12,
                'url' => 'https://www.pcauto.com.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:10:18',
                'updated_at' => '2019-12-13 18:10:18',
            ),
            48 => 
            array (
                'id' => 51,
                'title' => '车168',
                'navigation_category_id' => 12,
                'url' => 'https://www.che168.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:10:27',
                'updated_at' => '2019-12-13 18:10:27',
            ),
            49 => 
            array (
                'id' => 52,
                'title' => '中国移动',
                'navigation_category_id' => 11,
                'url' => 'http://www.10086.cn',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:10:38',
                'updated_at' => '2019-12-13 18:10:38',
            ),
            50 => 
            array (
                'id' => 53,
                'title' => '中国电信',
                'navigation_category_id' => 11,
                'url' => 'http://www.189.cn',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:10:49',
                'updated_at' => '2019-12-13 18:10:49',
            ),
            51 => 
            array (
                'id' => 54,
                'title' => '中国联通',
                'navigation_category_id' => 11,
                'url' => 'http://www.10010.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:10:58',
                'updated_at' => '2019-12-13 18:10:58',
            ),
            52 => 
            array (
                'id' => 55,
                'title' => '苹果手机',
                'navigation_category_id' => 11,
                'url' => 'https://www.apple.com/cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:11:08',
                'updated_at' => '2019-12-13 18:11:08',
            ),
            53 => 
            array (
                'id' => 56,
                'title' => '小米',
                'navigation_category_id' => 11,
                'url' => 'https://www.mi.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:11:16',
                'updated_at' => '2019-12-13 18:11:16',
            ),
            54 => 
            array (
                'id' => 57,
                'title' => '太平洋手机',
                'navigation_category_id' => 11,
                'url' => 'https://mobile.pconline.com.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:11:25',
                'updated_at' => '2019-12-13 18:11:25',
            ),
            55 => 
            array (
                'id' => 58,
                'title' => '华军软件园',
                'navigation_category_id' => 10,
                'url' => 'http://www.onlinedown.net/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:11:38',
                'updated_at' => '2019-12-13 18:11:38',
            ),
            56 => 
            array (
                'id' => 59,
                'title' => '天空下载',
                'navigation_category_id' => 10,
                'url' => 'http://www.skycn.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:11:47',
                'updated_at' => '2019-12-13 18:11:47',
            ),
            57 => 
            array (
                'id' => 60,
                'title' => '快科技',
                'navigation_category_id' => 10,
                'url' => 'http://www.mydrivers.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:11:57',
                'updated_at' => '2019-12-13 18:11:57',
            ),
            58 => 
            array (
                'id' => 61,
                'title' => '中关村下载',
                'navigation_category_id' => 10,
                'url' => 'http://xiazai.zol.com.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:12:07',
                'updated_at' => '2019-12-13 18:12:07',
            ),
            59 => 
            array (
                'id' => 62,
                'title' => '太平洋下载',
                'navigation_category_id' => 10,
                'url' => 'https://dl.pconline.com.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:12:19',
                'updated_at' => '2019-12-13 18:12:19',
            ),
            60 => 
            array (
                'id' => 63,
                'title' => '多特下载',
                'navigation_category_id' => 10,
                'url' => 'http://www.duote.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:12:30',
                'updated_at' => '2019-12-13 18:12:30',
            ),
            61 => 
            array (
                'id' => 64,
                'title' => '猫扑',
                'navigation_category_id' => 9,
                'url' => 'http://www.mop.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:12:41',
                'updated_at' => '2019-12-13 18:12:41',
            ),
            62 => 
            array (
                'id' => 65,
                'title' => 'QQ空间',
                'navigation_category_id' => 9,
                'url' => 'https://qzone.qq.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:12:52',
                'updated_at' => '2019-12-13 18:12:52',
            ),
            63 => 
            array (
                'id' => 66,
                'title' => '百度贴吧',
                'navigation_category_id' => 9,
                'url' => 'https://tieba.baidu.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:13:49',
                'updated_at' => '2019-12-13 18:13:49',
            ),
            64 => 
            array (
                'id' => 67,
                'title' => '豆瓣',
                'navigation_category_id' => 9,
                'url' => 'https://www.douban.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:13:58',
                'updated_at' => '2019-12-13 18:13:58',
            ),
            65 => 
            array (
                'id' => 68,
                'title' => '领英',
                'navigation_category_id' => 9,
                'url' => 'https://www.linkedin.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:14:07',
                'updated_at' => '2019-12-13 18:14:07',
            ),
            66 => 
            array (
                'id' => 69,
                'title' => '游民星空',
                'navigation_category_id' => 8,
                'url' => 'https://www.gamersky.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:14:17',
                'updated_at' => '2019-12-13 18:14:17',
            ),
            67 => 
            array (
                'id' => 70,
                'title' => '电玩巴士',
                'navigation_category_id' => 8,
                'url' => 'http://www.tgbus.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:14:26',
                'updated_at' => '2019-12-13 18:14:26',
            ),
            68 => 
            array (
                'id' => 71,
                'title' => '游侠网',
                'navigation_category_id' => 8,
                'url' => 'http://www.ali213.net/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:14:36',
                'updated_at' => '2019-12-13 18:14:36',
            ),
            69 => 
            array (
                'id' => 72,
                'title' => '4399小游戏',
                'navigation_category_id' => 8,
                'url' => 'http://www.4399.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:14:46',
                'updated_at' => '2019-12-13 18:14:46',
            ),
            70 => 
            array (
                'id' => 73,
                'title' => '多玩游戏',
                'navigation_category_id' => 8,
                'url' => 'http://www.duowan.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:14:55',
                'updated_at' => '2019-12-13 18:14:55',
            ),
            71 => 
            array (
                'id' => 74,
                'title' => '网易游戏',
                'navigation_category_id' => 8,
                'url' => 'http://game.163.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:15:07',
                'updated_at' => '2019-12-13 18:15:07',
            ),
            72 => 
            array (
                'id' => 75,
                'title' => '大众点评',
                'navigation_category_id' => 7,
                'url' => 'http://www.dianping.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:15:16',
                'updated_at' => '2019-12-13 18:15:16',
            ),
            73 => 
            array (
                'id' => 76,
                'title' => '链家网',
                'navigation_category_id' => 7,
                'url' => 'https://www.lianjia.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:15:29',
                'updated_at' => '2019-12-13 18:15:29',
            ),
            74 => 
            array (
                'id' => 77,
                'title' => '下厨房',
                'navigation_category_id' => 7,
                'url' => 'http://www.xiachufang.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:15:40',
                'updated_at' => '2019-12-13 18:15:40',
            ),
            75 => 
            array (
                'id' => 78,
                'title' => '美团网',
                'navigation_category_id' => 7,
                'url' => 'https://www.meituan.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:15:49',
                'updated_at' => '2019-12-13 18:15:49',
            ),
            76 => 
            array (
                'id' => 79,
                'title' => '豆果美食',
                'navigation_category_id' => 7,
                'url' => 'https://www.douguo.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:15:59',
                'updated_at' => '2019-12-13 18:15:59',
            ),
            77 => 
            array (
                'id' => 80,
                'title' => '果壳科技',
                'navigation_category_id' => 7,
                'url' => 'https://www.guokr.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:16:08',
                'updated_at' => '2019-12-13 18:16:08',
            ),
            78 => 
            array (
                'id' => 82,
                'title' => '招商银行',
                'navigation_category_id' => 6,
                'url' => 'http://www.cmbchina.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:16:27',
                'updated_at' => '2019-12-13 18:16:27',
            ),
            79 => 
            array (
                'id' => 83,
                'title' => '工商银行',
                'navigation_category_id' => 6,
                'url' => 'http://www.icbc.com.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:16:37',
                'updated_at' => '2019-12-13 18:16:37',
            ),
            80 => 
            array (
                'id' => 84,
                'title' => '建设银行',
                'navigation_category_id' => 6,
                'url' => 'http://www.ccb.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:16:56',
                'updated_at' => '2019-12-13 18:16:56',
            ),
            81 => 
            array (
                'id' => 85,
                'title' => '农业银行',
                'navigation_category_id' => 6,
                'url' => 'http://www.abchina.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:17:08',
                'updated_at' => '2019-12-13 18:17:08',
            ),
            82 => 
            array (
                'id' => 86,
                'title' => '中国银行',
                'navigation_category_id' => 6,
                'url' => 'http://www.boc.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:17:19',
                'updated_at' => '2019-12-13 18:17:19',
            ),
            83 => 
            array (
                'id' => 87,
                'title' => '交通银行',
                'navigation_category_id' => 6,
                'url' => 'http://www.bankcomm.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:17:31',
                'updated_at' => '2019-12-13 18:17:31',
            ),
            84 => 
            array (
                'id' => 88,
                'title' => '随心听',
                'navigation_category_id' => 16,
                'url' => 'http://fm.taihe.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:17:41',
                'updated_at' => '2019-12-13 18:17:41',
            ),
            85 => 
            array (
                'id' => 89,
                'title' => '网易云音乐',
                'navigation_category_id' => 16,
                'url' => 'https://music.163.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:17:51',
                'updated_at' => '2019-12-13 18:17:51',
            ),
            86 => 
            array (
                'id' => 90,
                'title' => 'QQ音乐',
                'navigation_category_id' => 16,
                'url' => 'https://y.qq.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:18:00',
                'updated_at' => '2019-12-13 18:18:00',
            ),
            87 => 
            array (
                'id' => 91,
                'title' => '酷狗',
                'navigation_category_id' => 16,
                'url' => 'http://www.kugou.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:18:09',
                'updated_at' => '2019-12-13 18:18:09',
            ),
            88 => 
            array (
                'id' => 92,
                'title' => '虾米音乐',
                'navigation_category_id' => 16,
                'url' => 'https://www.xiami.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:18:19',
                'updated_at' => '2019-12-13 18:18:19',
            ),
            89 => 
            array (
                'id' => 93,
                'title' => '音悦台',
                'navigation_category_id' => 16,
                'url' => 'http://www.yinyuetai.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2019-12-13 18:18:27',
                'updated_at' => '2019-12-13 18:18:27',
            ),
            90 => 
            array (
                'id' => 97,
                'title' => '稿定设计',
                'navigation_category_id' => 17,
                'url' => 'http://www.gaoding.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2020-01-02 10:57:44',
                'updated_at' => '2020-01-02 10:57:44',
            ),
            91 => 
            array (
                'id' => 98,
                'title' => '站酷',
                'navigation_category_id' => 17,
                'url' => 'https://www.zcool.com.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2020-01-02 11:01:16',
                'updated_at' => '2020-01-02 11:01:16',
            ),
            92 => 
            array (
                'id' => 99,
                'title' => '来画',
                'navigation_category_id' => 17,
                'url' => 'https://www.laihua.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2020-01-02 11:02:00',
                'updated_at' => '2020-01-02 11:02:00',
            ),
            93 => 
            array (
                'id' => 100,
                'title' => '花瓣',
                'navigation_category_id' => 17,
                'url' => 'https://huaban.com/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2020-01-02 11:03:47',
                'updated_at' => '2020-01-02 11:03:47',
            ),
            94 => 
            array (
                'id' => 101,
                'title' => '泼辣有图',
                'navigation_category_id' => 17,
                'url' => 'http://www.polayoutu.com',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2020-01-02 11:23:25',
                'updated_at' => '2020-01-02 11:23:25',
            ),
            95 => 
            array (
                'id' => 102,
                'title' => '微信编辑器',
                'navigation_category_id' => 17,
                'url' => 'https://edit.newrank.cn/',
                'sort' => 0,
                'views' => 0,
                'status' => 1,
                'user_id' => 0,
                'created_at' => '2020-01-02 11:36:21',
                'updated_at' => '2020-01-02 11:36:21',
            ),
        ));
        
        
    }
}